---
# Source: listener-operator/templates/storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: listeners.stackable.tech
provisioner: listeners.stackable.tech
volumeBindingMode: WaitForFirstConsumer
