---
# Source: commons-operator/templates/roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: commons-operator-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - secrets
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - patch # We need to add a label to the StatefulSet
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
