apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"networking","app.kubernetes.io/name":"knative-serving","app.kubernetes.io/version":"1.12.3","knative.dev/crd-install":"true"},"name":"clusterdomainclaims.networking.internal.knative.dev"},"spec":{"group":"networking.internal.knative.dev","names":{"categories":["knative-internal","networking"],"kind":"ClusterDomainClaim","plural":"clusterdomainclaims","shortNames":["cdc"],"singular":"clusterdomainclaim"},"scope":"Cluster","versions":[{"name":"v1alpha1","schema":{"openAPIV3Schema":{"description":"ClusterDomainClaim is a cluster-wide reservation for a particular domain name.","properties":{"apiVersion":{"description":"APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources","type":"string"},"kind":{"description":"Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds","type":"string"},"metadata":{"type":"object"},"spec":{"description":"Spec is the desired state of the ClusterDomainClaim. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status","properties":{"namespace":{"description":"Namespace is the namespace which is allowed to create a DomainMapping using this ClusterDomainClaim's name.","type":"string"}},"required":["namespace"],"type":"object"}},"type":"object"}},"served":true,"storage":true,"subresources":{"status":{}}}]}}
  creationTimestamp: "2024-01-27T03:05:18Z"
  generation: 1
  labels:
    app.kubernetes.io/component: networking
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.12.3
    knative.dev/crd-install: "true"
  name: clusterdomainclaims.networking.internal.knative.dev
  resourceVersion: "1813"
  uid: 04a30b84-11dc-42c5-bd59-e0cbb0d141ca
spec:
  conversion:
    strategy: None
  group: networking.internal.knative.dev
  names:
    categories:
    - knative-internal
    - networking
    kind: ClusterDomainClaim
    listKind: ClusterDomainClaimList
    plural: clusterdomainclaims
    shortNames:
    - cdc
    singular: clusterdomainclaim
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ClusterDomainClaim is a cluster-wide reservation for a particular
          domain name.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: 'Spec is the desired state of the ClusterDomainClaim. More
              info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
            properties:
              namespace:
                description: Namespace is the namespace which is allowed to create
                  a DomainMapping using this ClusterDomainClaim's name.
                type: string
            required:
            - namespace
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - knative-internal
    - networking
    kind: ClusterDomainClaim
    listKind: ClusterDomainClaimList
    plural: clusterdomainclaims
    shortNames:
    - cdc
    singular: clusterdomainclaim
  conditions:
  - lastTransitionTime: "2024-01-27T03:05:18Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-01-27T03:05:19Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
